package com.jailbird.textgeneration.config;

import com.jailbird.skills.textgeneration.TextGenerationServiceGrpc;
import com.jailbird.skills.textgeneration.TextGenerationServiceRest;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.reactive.function.server.RouterFunction;
import org.springframework.web.reactive.function.server.ServerResponse;

/**
 * Configuration for auto-generated REST endpoints from protoc-gen-spring-webflux.
 * 
 * This configuration wires the auto-generated REST handlers (from protoc-gen-spring-webflux) 
 * with our local gRPC service. The endpoints are automatically derived from 
 * google.api.http annotations in the proto files.
 */
@Configuration
public class AutoGeneratedRestConfig {

    /**
     * Creates a gRPC channel to connect to our local gRPC service.
     */
    @Bean
    public ManagedChannel grpcChannel() {
        return ManagedChannelBuilder.forAddress("localhost", 9090)
                .usePlaintext()
                .build();
    }

    /**
     * Creates a gRPC stub for making calls to the TextGeneration service.
     */
    @Bean
    public TextGenerationServiceGrpc.TextGenerationServiceStub textGenerationStub(ManagedChannel channel) {
        return TextGenerationServiceGrpc.newStub(channel);
    }

    /**
     * Creates the auto-generated REST handler that proxies HTTP calls to gRPC.
     * 
     * This handler is generated by protoc-gen-spring-webflux from our .proto file
     * and automatically maps google.api.http annotations to REST endpoints.
     */
    @Bean
    public TextGenerationServiceRest.TextGenerationServiceHandler autoGeneratedRestHandler(
            TextGenerationServiceGrpc.TextGenerationServiceStub stub) {
        
        return TextGenerationServiceRest.newGrpcProxyBuilder()
                .setStub(stub)
                .build();
    }

    /**
     * Registers the auto-generated REST routes.
     * 
     * These routes are automatically created from the google.api.http annotations
     * in our proto file during build time:
     * - POST /api/v1/text-generation/generate
     * - POST /api/v1/text-generation/generate-stream  
     * - GET /api/v1/text-generation/health
     */
    @Bean
    public RouterFunction<ServerResponse> autoGeneratedRoutes(
            TextGenerationServiceRest.TextGenerationServiceHandler handler) {
        
        return handler.allRoutes();
    }
}